### ISSUE TITLE
several errors

### ISSUE THREAD

**Issue by slothful-vassal** [ephes/kptncook#30]
Hello,

I'm trying to use your scripts to fetch kpntcook recipes and export them to mealie. But it does not work :(

kptncook kptncook-today --> is working fine, it lists all recipes
kptncook backup-favorites --> read timeout
kptncook save-todays-recipes --> unicode decode error

What I'm doing wrong here? Can you help me (again) please? (I'm running the script using powershell in Win 11)

Many thanks & Regards,
Matthias

**Comment by brotkrume** [comment]
I have deleted the kptncook.json and now it works :)

**Comment by brotkrume** [comment]
Sorry, still get timeout when backing up favorites. And how can I use the sharing links? The script can extract the uid from link, but can't find the recipe :(

Many thanks.,

**Comment by ephes** [comment]
> Sorry, still get timeout when backing up favorites.

Do you see any output at all? Maybe I should increase the timeout for `httpx` requests. But for me it looks quite fast (3.2s for 171 favorites):
```shell
╰─>$ kptncook backup-favorites                3283ms  So 10 Dez 09:59:57 2023
Found 171 favorites
Added 171 recipes to local repository
```

>  And how can I use the sharing links? The script can extract the uid from link, but can't find the recipe :(

Ah, there's a redirect when opening up the `https://share.kptncook.com`-urls in the browser. The final URL should work. I just added a snippet to get the redirect location automatically. So it now should also work with the original sharing URL.

> In Mealie, the images of the recipe steps are missing :(

Hmm, I can't get mealie to work anymore, so I cannot reproduce this, sorry.

thanks for your report and best regards
Jochen

**Comment by brotkrume** [comment]
Thank you very much. I'm able to get the recipe uid with the redirect url :)

'Found 999 favorites' ;) This huge amount could explain the timeout...

**Comment by ephes** [comment]
> Thank you very much. I'm able to get the recipe uid with the redirect url :)
> 
> 'Found 999 favorites' ;) This huge amount could explain the timeout...

Ok wow 😮 - and I'm a little bit suspicious about this number being correct 😄. Ok, deactivated the timeout, let's see what happens now.

**Comment by brotkrume** [comment]
thanks :) 

Offtopic: you don't use Mealie anymore? What's your new favorite recipe manager?

**Comment by slothful-vassal** [comment]
Hello,

I wish you a happy new year :)

Because I'm not familiar with python and need an android app allowing me to directely push the recipes to mealie, I have re-written your app as flutter app: [kptn_sync](https://github.com/slothful-vassal/kptn_sync).

Many thanks for your support :)


Regards
