### ISSUE TITLE
Export to Foodie Rest API

### ISSUE THREAD

**Issue by mikebgrep** [ephes/kptncook#42]
Hey, this is a very cool project, in my opinion.
I can propose to extend the functionality and add support to export the recipes in the Foodie application https://github.com/mikebgrep/foodie
I can expose endpoint for adding a recipe there.

**Comment by ephes** [comment]
Go for it 😄! No, you do not need to reverse the kptncook app. Just use the KPTNCOOK_API_KEY from the readme. It's the same for everyone.
